const emojiSearchTerms: { [key: string]: string[] } = {
    // Smileys & Emotion
    smile: ['😀', '😁', '😃', '😄', '😊', '🙂', '😺', '😸', '😻'],
    laugh: ['😂', '🤣', '😹'],
    wink: ['😉'],
    love_face: ['😍', '😘', '😗', '😙', '😚', '🥰', '😻'],
    kiss: ['💋', '😗', '😘', '😚', '😽'],
    happy: ['😊', '😄', '😃', '🙂', '😁', '😆'],
    sad: ['😔', '😞', '😢', '😭', '😿'],
    angry: ['😠', '😡', '🤬', '👿', '😾'],
    surprise: ['😲', '😯', '😳', '😮', '😱', '🙀'],
    confused: ['😕', '😟', '😐', '😑', '😶', '🙄'],
    cool: ['😎'],
    love_eyes: ['😍'],
    blush: ['😊', '☺️'],
    cry: ['😢', '😭', '😿'],
    fear: ['😨', '😰', '😱'],
    kiss_face: ['😗', '😘', '😚'],
    tongue: ['😛', '😜', '😝'],
    sleepy: ['😴', '😪'],
    sick: ['🤢', '🤮', '🤧', '🤒', '🤕'],
    devil: ['😈', '👿', '👹', '👺'],
    skull: ['💀', '☠️'],
    ghost: ['👻'],
    poop: ['💩'],
    clown: ['🤡'],
    robot: ['🤖'],
    
    // People & Body
    wave: ['👋'],
    hand: ['🤚', '✋', '🖐️', '👌', '🤌', '🤏'],
    thumbs_up: ['👍'],
    thumbs_down: ['👎'],
    fist: ['✊', '👊', '🤛', '🤜'],
    clap: ['👏'],
    muscle: ['💪'],
    pray: ['🙏'],
    love: ['❤️', '💘', '💖', '💗', '💓', '💕', '💞'],
    broken_heart: ['💔'],
    ok_hand: ['👌'],
    point_up: ['👆'],
    point_down: ['👇'],
    point_left: ['👈'],
    point_right: ['👉'],

    // Animals & Nature
    dog: ['🐶', '🐕', '🦮', '🐩', '🐕‍🦺'],
    cat: ['🐱', '🐈'],
    mouse: ['🐭', '🐁', '🖱️'],
    monkey: ['🐵', '🐒', '🦍'],
    lion: ['🦁'],
    tiger: ['🐯', '🐅'],
    horse: ['🐴', '🐎'],
    unicorn: ['🦄'],
    cow: ['🐮', '🐄', '🐂', '🐃'],
    pig: ['🐷', '🐖', '🐗'],
    frog: ['🐸'],
    rabbit: ['🐰', '🐇'],
    bear: ['🐻', '🐼'],
    koala: ['🐨'],
    panda: ['🐼'],
    bird: ['🐦', '🐧', '🦅', '🦆', '🦉'],
    chicken: ['🐔', '🐓'],
    penguin: ['🐧'],
    fish: ['🐟', '🐠', '🐡', '🦈'],
    whale: ['🐳', '🐋'],
    dolphin: ['🐬'],
    octopus: ['🐙'],
    crab: ['🦀'],
    lobster: ['🦞'],
    butterfly: ['🦋'],
    bug: ['🐛', '🐜', '🐞'],
    spider: ['🕷️', '🕸️'],
    flower: ['🌸', '🌼', '🌻', '🌺', '🌷'],
    tree: ['🌳', '🌲'],
    cactus: ['🌵'],
    leaf: ['🍃', '🍂', '🍁'],
    mushroom: ['🍄'],
    fire: ['🔥'],
    sun: ['☀️', '🌞'],
    moon: ['🌝', '🌛', '🌜', '🌚'],
    cloud: ['☁️', '🌤️', '⛅', '🌥️'],
    rainbow: ['🌈'],
    lightning: ['⚡'],
    snowflake: ['❄️'],
    star: ['⭐', '🌟'],

    // Food & Drink
    apple: ['🍎', '🍏'],
    banana: ['🍌'],
    grapes: ['🍇'],
    watermelon: ['🍉'],
    strawberry: ['🍓'],
    lemon: ['🍋'],
    cherries: ['🍒'],
    peach: ['🍑'],
    pineapple: ['🍍'],
    mango: ['🥭'],
    carrot: ['🥕'],
    potato: ['🥔'],
    corn: ['🌽'],
    tomato: ['🍅'],
    avocado: ['🥑'],
    bread: ['🍞'],
    cheese: ['🧀'],
    meat: ['🍖', '🍗'],
    bacon: ['🥓'],
    hamburger: ['🍔'],
    fries: ['🍟'],
    pizza: ['🍕'],
    hot_dog: ['🌭'],
    taco: ['🌮'],
    burrito: ['🌯'],
    egg: ['🥚'],
    salad: ['🥗'],
    popcorn: ['🍿'],
    ice_cream: ['🍦', '🍨'],
    cake: ['🍰', '🎂'],
    donut: ['🍩'],
    coffee: ['☕'],
    tea: ['🍵'],
    beer: ['🍺', '🍻'],
    wine: ['🍷'],
    cocktail: ['🍸'],
    whiskey: ['🥃'],
    milk: ['🥛'],
    juice: ['🧃'],
    soda: ['🥤'],

    // Travel & Places
    car: ['🚗', '🚘'],
    taxi: ['🚕'],
    bus: ['🚌'],
    train: ['🚂', '🚆', '🚇'],
    airplane: ['✈️', '🛫', '🛬'],
    rocket: ['🚀'],
    bicycle: ['🚲'],
    motorcycle: ['🏍️'],
    ship: ['🚢'],
    boat: ['⛵'],
    city: ['🏙️'],
    home: ['🏠', '🏡'],
    building: ['🏢', '🏬'],
    hospital: ['🏥'],
    church: ['⛪'],
    mosque: ['🕌'],
    temple: ['🛕'],
    beach: ['🏖️'],
    mountain: ['⛰️', '🏔️'],
    volcano: ['🌋'],
    camping: ['🏕️'],
    desert: ['🏜️'],

    // Activities & Sports
    soccer: ['⚽'],
    baseball: ['⚾'],
    basketball: ['🏀'],
    football: ['🏈'],
    tennis: ['🎾'],
    volleyball: ['🏐'],
    golf: ['⛳'],
    fishing: ['🎣'],
    skiing: ['🎿'],
    snowboard: ['🏂'],
    swimming: ['🏊‍♂️', '🏊‍♀️'],
    running: ['🏃‍♂️', '🏃‍♀️'],
    cycling: ['🚴‍♂️', '🚴‍♀️'],
    weightlifting: ['🏋️‍♂️', '🏋️‍♀️'],
    boxing: ['🥊'],
    martial_arts: ['🥋'],
    yoga: ['🧘‍♂️', '🧘‍♀️'],
    dancing: ['💃', '🕺'],
    party: ['🎉', '🥳'],
    video_games: ['🎮'],
    music: ['🎵', '🎶', '🎼'],
    guitar: ['🎸'],
    drum: ['🥁'],
    piano: ['🎹'],
    microphone: ['🎤'],
    film: ['🎥', '🎬'],
    camera: ['📷', '📸'],

    // Objects
    phone: ['📱', '📞'],
    laptop: ['💻'],
    computer: ['🖥️'],
    keyboard: ['⌨️'],
    printer: ['🖨️'],
    tv: ['📺'],
    light_bulb: ['💡'],
    flashlight: ['🔦'],
    book: ['📖', '📚'],
    pencil: ['✏️'],
    pen: ['🖊️'],
    paintbrush: ['🖌️'],
    scissors: ['✂️'],
    tools: ['🔧', '🔨', '🛠️'],
    lock: ['🔒', '🔓'],
    key: ['🔑'],
    clock: ['🕰️', '⏰', '⏱️', '⌚'],
    calendar: ['📅', '📆'],
    envelope: ['✉️'],
    package: ['📦'],
    money: ['💵', '💴', '💶', '💷', '💰'],
    credit_card: ['💳'],
    fire_extinguisher: ['🧯'],
    shopping_cart: ['🛒'],
    gift: ['🎁'],
    trophy: ['🏆'],
    medal: ['🏅'],

    // Symbols
    heart: ['❤️', '💛', '💚', '💙', '💜', '🖤', '🤍'],
    water: ['💧', '🌊'],
    earth: ['🌍', '🌎', '🌏'],
    peace: ['☮️'],
    cross: ['✝️'],
    crescent_moon: ['☪️'],
    yin_yang: ['☯️'],
    check_mark: ['✅'],
    x_mark: ['❌'],
    question_mark: ['❓'],
    exclamation_mark: ['❗', '‼️'],
    arrow: ['➡️', '⬅️', '⬆️', '⬇️'],
    recycle: ['♻️'],
    warning: ['⚠️'],
    no_entry: ['🚫'],
    radiation: ['☢️'],
    biohazard: ['☣️'],
    infinity: ['♾️'],
    flag: ['🚩', '🏳️', '🏴'],
    skull_crossbones: ['☠️'],
    umbrella: ['☂️', '🌂'],
    anchor: ['⚓'],

    // Flags
    usa: ['🇺🇸'],
    uk: ['🇬🇧'],
    canada: ['🇨🇦'],
    france: ['🇫🇷'],
    germany: ['🇩🇪'],
    italy: ['🇮🇹'],
    spain: ['🇪🇸'],
    japan: ['🇯🇵'],
    china: ['🇨🇳'],
    korea: ['🇰🇷'],
    russia: ['🇷🇺'],
    brazil: ['🇧🇷'],
    india: ['🇮🇳'],
    mexico: ['🇲🇽'],
    australia: ['🇦🇺'],
    south_africa: ['🇿🇦'],
};

export default emojiSearchTerms;